FROM nvidia/cuda as base

RUN apt-get update --fix-missing

RUN apt-get -y install python3-pip python3-yaml

RUN python3 -m pip install numpy pandas pyarrow jupyter

RUN python3 -m pip install nose
RUN ln -sf nosetests /usr/local/bin/nosetests3

# NOTE. Use ./scripts/docker_*.sh for building Dockerfiles.
